name: wvac CD
on:
  push:
    branches:
      - "master"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "testing wvac master"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: run unit test
        run: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3
  
  deploy:
    runs-on: ubuntu-latest
    name: "deploy wvac master"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fachrudin27/wvac:latest
      
      - name: update aws instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker stop wvac_be
            sudo docker container rm wvac_be
            sudo docker pull fachrudin27/wvac:latest
            sudo docker run -d -v $PWD/.env:/.env -p 80:8000 --name wvac_be fachrudin27/wvac:latest