name: wvac dev CI
on:
  pull_request:
    branches:
      - "development"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "testing wvac"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: run unit test
        run: go test -v ./...